[theme]
base = "dark"
primaryColor = "#00F0FF"
backgroundColor = "#050811"
secondaryBackgroundColor = "#0A0F1D"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
